### ISSUE TITLE
You can play 4k videos on youtube !?

### ISSUE THREAD

**Issue by ExodazTH** [salsadal/Z590-Nativo#1]
I play videos FHD on youtube that's pretty very smooth. but adjust to 4k 60fps very lag and frame drop.

You Have same problem ?

**Comment by salsadal** [comment]
I can play 4k 60fps videos on Youtube perfectly, no frame drops. Maybe it's your Internet connect or disk speed?

**Comment by ExodazTH** [comment]
> 

I use NVME Disk and on windows i play 4k youtube fine.

**Comment by ExodazTH** [comment]
> I can play 4k 60fps videos on Youtube perfectly, no frame drops. Maybe it's your Internet connect or disk speed?

You can capture stat for nerds on youtube when you play 4k 60 .

**Comment by salsadal** [comment]
<img width="660" alt="Screen Shot 2022-02-17 at 06 50 21" src="https://user-images.githubusercontent.com/42156788/154450753-df95f1c2-3c4d-47a0-846b-255d06c7a835.png">
